name: build x64 release ci

on: 
  push:
    branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@main
      - name: Build with MSBuild
        run: msbuild CS2_External\CS2_External.vcxproj /p:Configuration=Release /p:Platform=x64
      - name: Rename EXE to AimStar-${{github.sha}}.exe
        run: |
          del AimStar-*.exe
          ren AimStar.exe AimStar-${{github.sha}}.exe
        working-directory: CS2_External\x64\Release\
      - name: Upload the output
        uses: actions/upload-artifact@main
        with:
          name: ci
          path: CS2_External\x64\Release\*
  create_release:
    runs-on: ubuntu-latest
    needs: [build]
    name: Create Release
    steps:
      - uses: actions/checkout@main
      - name: Download Artifact
        uses: actions/download-artifact@main
      - run: ls -R
      - name: Zip ci
        uses: vimtor/action-zip@master
        with:
          files: ./ci/AimStar-${{github.sha}}.exe           
          dest: AimStar-Autobuild.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run latest-tag
        uses: EndBug/latest-tag@main
        with:
          ref: autobuild
      - name: automatic Release ci
        uses: softprops/action-gh-release@master
        with:
          name: autobuild [${{github.sha}}]
          tag_name: autobuild
          body: |
            **This release has been built by Github Actions, and may contains some issues**
            [Link to build](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            Full Commit Hash of Latest autobuild:
            ```
            ${{github.sha}}
            ```
            No support for any autobuild version except the latest autobuild
            Try llvm build if msvc build doesn't works right
          files: |
            AimStarR0-Autobuild.zip
          prerelease: true
